### ISSUE TITLE
Benutzerhandbuch

### ISSUE THREAD

**Issue by AnnaSchwarze** [hansesm/BiberDAMM#62]
Ich bin gerade dabei das Benutzerhandbuch zu schreiben. Ich habe die Kapitel jetzt in die jeweiligen Rollen unterteilt und darunter in den Unterkapiteln die Funktionen beschrieben. Einige Funktionen wiederholen sich bei den anderen Rollen. Jetzt ist die Frage, soll ich es so beibehalten und bei den wiederholenden Funktionen bei den weiteren Rollen einfach schreiben "siehe unter Punkt xy" oder soll ich lieber die Gliederung nach Funktionen unterteilen und die jeweiligen Rollen dazu schreiben. 
Am besten schaut ihr euch das ganze mal unter Dokumente an und schreibt mir hier, was ihr denkt, bevor ich irgendwie doppelte oder unnötige Arbeit mache.
Danke.
@jonask94 @hansesm @robinchristes @jp-gthb @LJentzsch

**Comment by LJentzsch** [comment]
Gedruckt, Gespeichert und hoffentlich fertig!^^
