### ISSUE TITLE
Präsentation für Freitag

### ISSUE THREAD

**Issue by robinchristes** [hansesm/BiberDAMM#69]
Damit alle mitlesen können, würde ich das einmal hier starten;

In der Mail von dem Kerl stand ja drin, wir sollten es nach Möglichkeit anhand daran präsentieren, dass jeder eine Rolle einnimmt und dann einmal den Use-Case durchspielt, die Frage wäre da jetzt, wer was machen würde oder wie wir die Präsentation sonst gestalten wollen

**Comment by LJentzsch** [comment]
alles vorbereitet!
